#!/usr/bin/env bash

name=$(pacmd list-cards | awk '/bluez_card/ {print $2}')
name=${name:1:-1}

profile=$(pacmd list-cards | awk '/active profile: <a2dp_sink_ldac>|headset_head_unit>/ {print $3}')
profile=${profile:1:-1}

profile1="a2dp_sink_ldac"
profile2="headset_head_unit"

if [ -n ${name} ];then
    if [ ${profile} == ${profile1} ]; then
        pacmd set-card-profile "$name" "$profile2"
    else
        pacmd set-card-profile "$name" "$profile1"
    fi
else
    printf "Device not connected\n"
fi
