#!/usr/bin/env bash

kitty_template="$HOME/.config/kitty/kitty_template.conf"
termite_template="$HOME/.config/termite/config_template"
kitty="$HOME/.config/kitty/kitty.conf"
termite="$HOME/.config/termite/config"
icons_dir="$HOME/.config/xmobar/icons"

[[ ! -d "$icons_dir" ]] && mkdir "$icons_dir"

hash convert
[[ $? -eq 1 ]] && (printf "\nimagemagick is not installed\nInstalling..."; yay -S imagemagick --noconfirm)

function icons {
	for i in "$HOME"/.config/xmobar/images/*
		do
		name=$(basename "$i" | cut -d '.' -f 1)
		if [[ "$i" =~ "haskell" ]]; then
			ffmpeg -i "$i" -vf scale="$1":"$2" "$(basename "$i")"
		else
			ffmpeg -i "$i" -vf scale="$3":"$3" "$(basename "$i")"
		fi
		convert "$(basename "$i")" "$name.xpm"
		mv ./*.xpm "$icons_dir"
		rm ./*png
	done
}

type=$(cat /sys/class/dmi/id/chassis_type)

case $type in
	3 )
		size=14
		icons "27" "17" "16"
		;;
	* )
		size=12
		icons "25" "15" "14"
		;;
esac

if [ ! -f "$kitty" ]; then
	cp "$kitty_template" "$kitty"
	sed -i s/value/$size/g "$kitty"
fi
	
if [ ! -f "$termite" ]; then
	cp "$termite_template" "$termite"
	sed -i s/value/$size/g "$termite"
fi
