#!/usr/bin/env bash

type=$(cat /sys/class/dmi/id/chassis_type)

case $type in
	3 )
		size=13
		;;
	* )
		size=11
		;;
esac

kitty="$HOME/.config/kitty/kitty.conf"
termite="$HOME/.config/termite/config"

sed -i s/size_value/$size/g "$kitty" "$termite"
