#!/usr/bin/env bash

icons_dir="$HOME/.config/xmobar/icons"

[[ ! -d "$icons_dir" ]] && mkdir "$icons_dir"

for i in "$HOME"/.config/xmobar/images/*
    do
    name=$(basename "$i" | cut -d '.' -f 1)
    if [[ "$i" =~ "haskell" ]]; then
        ffmpeg -loglevel error -i "$i" -vf scale=25:15 "$(basename "$i")"
    else
        ffmpeg -loglevel error -i "$i" -vf scale=18:14 "$(basename "$i")"
    fi
    convert "$(basename "$i")" "$name.xpm"
    mv ./*.xpm "$icons_dir"
    rm ./*png
done
