#!/usr/bin/env bash

connected=$(bluetoothctl -- info | awk '/Connected/ {print $2}')
profile=$(pacmd list-cards | awk '/active profile: <a2dp_sink_ldac>|headset_head_unit>/ {print $3}')
profile=${profile:1:-1}

if [[ $connected == "yes" ]]; then
    headset="<fn=2><fc=#717733> </fc></fn>"
    if [[ $profile == "a2dp_sink_ldac" ]]; then
        mic="<fn=1><fc=#A54242> </fc></fn>"
    else
        mic="<fn=1><fc=#717733> </fc></fn>"
    fi
else
    headset="<fn=2><fc=#A54242> </fc></fn>"
    mic="<fn=1><fc=#A54242> </fc></fn>"
fi

printf "$headset$mic"
