#!/usr/bin/env bash

state="$(mocp -Q %state 2>&1)"
total_length=56

if [[ ! "$state" =~ "FATAL" ]]; then
    if [ "$(mocp -Q %state)" != "STOP" ];then
        SONG=$(mocp -Q %song)

        if [ -n "$SONG" ]; then
            echo "$SONG - $(mocp -Q %album)"
        else
            name=$(basename "$(mocp -Q %file)")
            song_name=$(echo "$name" | cut -d '.' -f 1)
            song_name_length=${#song_name}
            if [[ "$song_name_length" -ge 30 ]]; then
                song_name=${song_name:0:30}"..."
            fi
            result=$(( (total_length - song_name_length - 3 - 15)/2 ))
            for i in $(seq 1 $result); do echo -n " "; done
            printf " <fc=#222222><fn=1></fn></fc><fn=0><fc=#7B9246,#222222> </fc></fn><fc=#6C99BB,#222222>%s </fc><fc=#D0D0D0,#222222>[%s][%s]</fc><fc=#222222><fn=1></fn></fc>" "$song_name" $(mocp -Q %ct) $(mocp -Q %tt)
            for i in $(seq 1 $result); do echo -n " "; done
        fi

        if [ "$1" == "moc" ]; then
            notify-send.sh -R /tmp/id_file -t 2000 -i multimedia-player "$song_name"
        fi
    else
        echo ""
    fi
fi
