#!/usr/bin/env bash

if [ "$1" == "updates" ]; then
	notify-send.sh -R id_file -i dialog-information "Obtaining updates"
fi

updates_arch=$(checkupdates 2> /dev/null)
updates_aur=$(checkupdates-aur 2> /dev/null)
n_updates_arch=$(echo "$updates_arch" | sed '/^$/d' | wc -l)
n_updates_aur=$(echo "$updates_aur" | sed '/^$/d' | wc -l)

n_updates=$(("$n_updates_arch" + "$n_updates_aur"))

case "$1" in
	updates)
		if [ $n_updates -eq 0 ]; then
			notify-send.sh -R id_file -i dialog-information "System up to date"
		else
			notify-send.sh -R id_file -t 5000 -i dialog-information "Available updates" "$updates_arch\n$updates_aur"
		fi
		;;
	*)
		if [ "$n_updates" -eq 0 ]; then
			echo "<icon=ok.xpm/>"
		else
			echo "<icon=updates.xpm/> $n_updates"
		fi
		;;
esac
