#!/usr/bin/env bash

case "$1" in
    updates)
        if [ -f /tmp/updates.bk ]; then
            file="/tmp/updates.bk"
        else
            file="/tmp/updates"
        fi
        if [ -z $(cat $file) ]; then
            notify-send.sh -R /tmp/id_file -i dialog-information "System up to date"
        else
            temp=$(cat $file)
            notify-send.sh -R /tmp/id_file -t 3000 -i dialog-information "Available updates" "$temp"
        fi
        ;;
    *)
        major="5.13."
        release="$(uname -r | sed "s/$major\(.*\)-xanmod1/\1/")"

        url=$(curl -u MiguelazoDS:"$(cat ~/.scripts/github_token)" "https://api.github.com/repos/xanmod/linux/releases" | grep -E "browser_download_url.*${major}[0-9]{2}-xanmod1.*\/.*$release.*--.*" | cut -d'"' -f4)

        xanmod_update="$(basename "$url" | sed -e 's/--/ -> /g' -e 's/patch-\(.*\)\.xz/\1/g')"

        updates_arch=$(checkupdates+aur 2> /dev/null)
        n_updates_arch=$(echo "$updates_arch" | sed '/^$/d' | wc -l)
        n_xanmod_patch=$(echo "$url" | sed '/^$/d' | wc -l)

        n_updates=$(("$n_updates_arch" + "$n_xanmod_patch"))

        if [ -f /tmp/updates ]; then
            cp /tmp/updates /tmp/updates.bk
            printf "%s\n%s" "$updates_arch" "$xanmod_update" > /tmp/updates
            rm /tmp/updates.bk
        else
            printf "%s\n%s" "$updates_arch" "$xanmod_update" > /tmp/updates
        fi

        if [ "$n_updates" -eq 0 ]; then
            echo "<fn=2> </fn>"
        else
            echo "<fn=2> </fn>$n_updates"
        fi
        ;;
esac
