#!/usr/bin/env bash

MUTE=$(pamixer --get-mute)

if [ "$MUTE" == "true" ]; then
    COLOUR="#A54242"
else
    COLOUR="#FDD29E"
fi

VALUE=$(pamixer --get-volume)

if [ "$MUTE" == "false" ]; then
    if [[ $((VALUE)) -ge 0 && $((VALUE)) -le 33 ]]; then
        echo "<fn=2>奄</fn> <fc=$COLOUR>$VALUE</fc>%"
    elif [[ $((VALUE)) -gt 33 && $((VALUE)) -le 66 ]]; then
        echo "<fn=2>奔</fn> <fc=$COLOUR>$VALUE</fc>%"
    else
        echo "<fn=2>墳</fn> <fc=$COLOUR>$VALUE</fc>%"
    fi
else
    echo "<fn=2>婢</fn> <fc=$COLOUR>Mute</fc>"
fi
