#!/usr/bin/env bash

MUTE=$(pamixer --get-mute)

if [ "$MUTE" == "true" ]; then
    COLOUR="#A54242"
else
    COLOUR="#6C99BB"
fi

VALUE=$(pamixer --get-volume)

if [ "$MUTE" == "false" ]; then
    if [[ $((VALUE)) -ge 0 && $((VALUE)) -le 33 ]]; then
        echo "<fc=#222222><fn=1></fn></fc><fn=0><fc=#6C99BB,#222222> </fc></fn><fc=$COLOUR,#222222>$VALUE%</fc><fc=#222222><fn=1></fn></fc>"
    elif [[ $((VALUE)) -gt 33 && $((VALUE)) -le 66 ]]; then
        echo "<fc=#222222><fn=1></fn></fc><fn=0><fc=#6C99BB,#222222> </fc></fn><fc=$COLOUR,#222222>$VALUE%</fc><fc=#222222><fn=1></fn></fc>"
    else
        echo "<fc=#222222><fn=1></fn></fc><fn=0><fc=#6C99BB,#222222> </fc></fn><fc=$COLOUR,#222222>$VALUE%</fc><fc=#222222><fn=1></fn></fc>"
    fi
else
    echo "<fc=#222222><fn=1></fn></fc><fn=0><fc=#6C99BB,#222222>婢 </fc></fn><fc=$COLOUR,#222222>Mute</fc><fc=#222222><fn=1></fn></fc>"
fi
