#!/usr/bin/env bash

source $HOME/.config/xmobar/scripts/colors

MUTE=$(pamixer --get-mute)

if [ "$MUTE" == "true" ]; then
    COLOUR="$fgRed"
else
    COLOUR="$fg"
fi

VALUE=$(pamixer --get-volume)

if [ "$MUTE" == "false" ]; then
    if [[ $((VALUE)) -ge 0 && $((VALUE)) -le 33 ]]; then
        echo "<fc=$bg><fn=1></fn></fc><fn=0><fc=$fg,$bg> </fc></fn><fc=$COLOUR,$bg>$VALUE%</fc><fc=$bg><fn=1></fn></fc>"
    elif [[ $((VALUE)) -gt 33 && $((VALUE)) -le 66 ]]; then
        echo "<fc=$bg><fn=1></fn></fc><fn=0><fc=$fg,$bg> </fc></fn><fc=$COLOUR,$bg>$VALUE%</fc><fc=$bg><fn=1></fn></fc>"
    else
        echo "<fc=$bg><fn=1></fn></fc><fn=0><fc=$fg,$bg> </fc></fn><fc=$COLOUR,$bg>$VALUE%</fc><fc=$bg><fn=1></fn></fc>"
    fi
else
    echo "<fc=$bg><fn=1></fn></fc><fn=0><fc=$fg,$bg>婢 </fc></fn><fc=$COLOUR,$bg>Mute</fc><fc=$bg><fn=1></fn></fc>"
fi
