#!/usr/bin/env bash

function icon {
	case $1 in
		01d ) icon="01d.xpm"
			  ;;
		01n ) icon="01n.xpm"
			  ;;
		02d ) icon="02d.xpm"
			  ;;
		02n ) icon="02n.xpm"
			  ;;
		03? ) icon="03.xpm"
			  ;;
		04? ) icon="04.xpm"
			  ;;
		09? ) icon="09.xpm"
			  ;;
		10d ) icon="10d.xpm"
			  ;;
		10n ) icon="10n.xpm"
			  ;;
		11? ) icon="11.xpm"
			  ;;
		13? ) icon="13.xpm"
			  ;;
		50? ) icon="50.xpm"
			  ;;
	esac

	echo "<icon=$icon/>"
}

url="https://api.openweathermap.org/data/2.5/weather?id=3860259&appid=$(cat "$HOME"/.config/xmobar/scripts/apikey)&units=metric"

info=$(curl "$url")

weather=$(echo "$info" | jq '.weather' | jq '.[].description' | sed -e 's/^"//' -e 's/"$//')

icon_code=$(echo "$info" | jq '.weather' | jq '.[].icon' | sed -e 's/^"//' -e 's/"$//')

temp=$(echo "$info" | jq '.main' | jq '.temp' | sed -e 's/^"//' -e 's/"$//')

printf "%s %sºC, %s" "$(icon "$icon_code")" "$temp" "$weather"
