#!/usr/bin/env bash

if [ "$1" == "--extended" ]; then
	notify-send.sh -R id_file -i dialog-information "Obtaining weather"
fi

function icon {
	case "$1" in
		01d ) icon="01d.xpm"
			  ;;
		01n ) icon="01n.xpm"
			  ;;
		02d ) icon="02d.xpm"
			  ;;
		02n ) icon="02n.xpm"
			  ;;
		03? ) icon="03.xpm"
			  ;;
		04? ) icon="04.xpm"
			  ;;
		09? ) icon="09.xpm"
			  ;;
		10d ) icon="10d.xpm"
			  ;;
		10n ) icon="10n.xpm"
			  ;;
		11? ) icon="11.xpm"
			  ;;
		13? ) icon="13.xpm"
			  ;;
		50? ) icon="50.xpm"
			  ;;
	esac

	echo "<icon=$icon/>"
}

url="https://api.openweathermap.org/data/2.5/weather?id=3860259&appid=$(cat "$HOME"/.config/xmobar/scripts/apikey)&units=metric"

info=$(curl "$url")

weather=$(echo "$info" | jq '.weather' | jq '.[].description' | sed -e 's/^"//' -e 's/"$//')

icon_code=$(echo "$info" | jq '.weather' | jq '.[].icon' | sed -e 's/^"//' -e 's/"$//')

temp=$(echo "$info" | jq '.main' | jq '.temp' | sed -e 's/^"//' -e 's/"$//')

case "$1" in
	--extended ) temp_min=$(echo "$info" | jq '.main' | jq '.temp_min' | sed -e 's/^"//' -e 's/"$//')
			   temp_max=$(echo "$info" | jq '.main' | jq '.temp_max' | sed -e 's/^"//' -e 's/"$//')
			   feels_like=$(echo "$info" | jq '.main' | jq '.feels_like' | sed -e 's/^"//' -e 's/"$//')
			   humidity=$(echo "$info" | jq '.main' | jq '.humidity' | sed -e 's/^"//' -e 's/"$//')
			   icon=$(icon "$icon_code")
			   icon_name=$(echo "$icon" | cut -d '=' -f2 | cut -d '.' -f1)
			   full_info=$(printf "\nToday\n====\n\nFeels_like: %sºC\nTemp. min: %sºC\nTemp. max: %sºC\nHumidity: %s%%" "$feels_like" "$temp_min" "$temp_max" "$humidity")
			   notify-send.sh -R id_file -i /home/miguel/.config/xmobar/images/"$icon_name".png "Extended weather" "$full_info"
			   ;;
	forecast ) echo forecast
			   ;;
	* )        printf "%s %sºC, %s" "$(icon "$icon_code")" "$temp" "$weather"
			   ;;
esac
