#!/usr/bin/env bash

hash snapper
[ $? -eq 1 ] && (printf "\nSnapper not installed.\nInstalling..."; yay -S snapper --noconfirm)

sudo snapper -c root create-config /
sudo btrfs subvolume delete /.snapshots
sudo mkdir -p /.snapshots

partition=$(df -hT | awk '/\/$/ {print $1}')

uuid=$(sudo sh -c "blkid | grep $partition | cut -d ' ' -f2 | tr -d '\"'")

sudo sh -c 'echo "# /dev/nvme1n1p6" >> /etc/fstab'
# UUID=......         /.snapshots         btrfs           rw-relatime,compress=lzo,space_cache,subvol=/@snapshots,subvol=@snapshots   0   0
sudo sh -c "echo \"${uuid}   /.snapshots  	btrfs     	rw,noatime,compress=lzo,ssd,space_cache=v2,subvol=/@snapshots	0 0\" >> /etc/fstab"

sudo mount /.snapshots

echo "Needs reboot"
