#!/usr/bin/env bash

[[ ! -d ../icons ]] && mkdir ../icons

for i in *
do
	name=$(echo "$i" | cut -d '.' -f 1)
	if [[ "$i" =~ "speed" ]]; then
		ffmpeg -i "$i" -vf scale=12:12 "z$i"
	elif [[ "$i" =~ "asterisk" ]]; then
		ffmpeg -i "$i" -vf scale=8:8 "z$i"
	elif [[ "$i" =~ "02" ]]; then
		ffmpeg -i "$i" -vf scale=23:15 "z$i"
	elif [[ "$i" =~ "03"|"04" ]]; then
		ffmpeg -i "$i" -vf scale=24:15 "z$i"
	elif [[ "$i" =~ "09" ]]; then
		ffmpeg -i "$i" -vf scale=16:15 "z$i"
	elif [[ "$i" =~ "11" ]]; then
		ffmpeg -i "$i" -vf scale=18:15 "z$i"
	elif [[ "$i" =~ "13" ]]; then
		ffmpeg -i "$i" -vf scale=15:16 "z$i"
	elif [[ "$i" =~ "50" ]]; then
		ffmpeg -i "$i" -vf scale=25:15 "z$i"
	elif [[ "$i" =~ "haskell" ]]; then
		ffmpeg -i "$i" -vf scale=27:17 "z$i"
	else
		ffmpeg -i "$i" -vf scale=16:16 "z$i"
	fi
	convert "z$i" "$name.xpm"
	mv ./*.xpm "$HOME"/.config/xmobar/icons
	rm z*
done
