#!/usr/bin/env bash

[[ ! -d ../icons ]] && mkdir ../icons

for i in * 
do 
	name=$(echo "$i" | cut -d '.' -f 1)
	if [[ "$i" =~ "haskell" ]]; then
		ffmpeg -i "$i" -vf scale=25:15 "z$i"
	else
		ffmpeg -i "$i" -vf scale=14:14 "z$i"
	fi
	convert "z$i" "$name.xpm"
	mv ./*.xpm "$HOME"/.config/xmobar/icons
	rm z*
done
