#!/usr/bin/env bash

source $HOME/.config/xmonad/xmobar_scripts/colors

function format {
    total=$(free -m| awk '/^Mem:/ {printf "%.3f", $2}')
    line_length="                         "
    proc="$1"
    size=$(echo "$2"*"$total"/100 | bc -l)
    printf "%s%s%.2f MiB\n" "${proc,,}" "${line_length:${#proc}}" "$size"
}

function update {
    ram=$(free -h| awk '/^Mem:/ {printf  "RAM:\n\nUsed: %s, Total: %s\n\n", $3, $2}')
    swap=$(free -h| awk '/^Swap:/ {printf  "SWAP:\n\nUsed: %s, Total: %s\n\n", $3, $2}')
    processes=$(ps axcho comm --sort=-%mem | head -20)
    mem=$(ps axcho %mem --sort=-%mem | head -20)
    IFS=$'\n' processes=($processes)
    IFS=$'\n' mem=($mem)
    var=$(for i in {0..19}
    do
        format "${processes[$i]}" "${mem[$i]}"
    done)
}

function gpu_mem {
    perc=$(nvidia-smi | head -n 10 | tail -n 1 | cut -d '|' -f 3 | awk '{used=($1+0)*100/($3+0); printf "%.f", used}')
    if [[ $((perc)) -ge 75 ]]; then
        echo "<fc=$fgRed,$bg>GPU:${perc}%</fc><fc=$bg><fn=1></fn></fc>"
    else
        echo "<fc=$fg,$bg>GPU:${perc}%</fc><fc=$bg><fn=1></fn></fc>"
    fi
}

duration=3
start_time=$(( SECONDS ))

case "$1" in
    --details)
        while [ $(( SECONDS )) -lt $(( start_time + duration )) ]
        do
            update
            notify-send.sh -R /tmp/id_file -i dialog-information -t 3000 "Memory info" "\n$ram\n\n$swap\n\n$var"
            sleep 0.01
            notify-send.sh -R /tmp/id_file -i dialog-information -t 100 "Memory info" "\n$ram\n\n$swap\n\n$var"
        done
        ;;
    *)
        free | awk -v bg="$bg" -v fg="$fg" '/^Mem:/ { used=(100*$3)/($2); printf "<fc=%s><fn=1></fn></fc><fc=%s,%s><fn=0> </fn>%.1f%%.2fGi</fc>", bg, fg, bg, used, $2/(1024*1024)}'
        gpu_mem
        ;;
esac
