#!/usr/bin/env bash

source $HOME/.config/xmonad/xmobar_scripts/colors

state="$(mocp -Q %state 2>&1)"
total_length=30
limit=15

if [[ ! "$state" =~ "FATAL" ]]; then
    if [ "$(mocp -Q %state)" != "STOP" ];then
        SONG=$(mocp -Q %song)

        if [ -n "$SONG" ]; then
            echo "$SONG - $(mocp -Q %album)"
        else
            name=$(basename "$(mocp -Q %file)")
            song_name=$(echo "$name" | cut -d '.' -f 1)
            song_name_length=${#song_name}
            if [[ "$song_name_length" -ge $limit ]]; then
                song_name=${song_name:0:$limit}"..."
            fi
            result=$(( (total_length - song_name_length - 3 - 15)/2 ))
            for i in $(seq 1 $result); do echo -n " "; done
            printf " <fc=$bg><fn=1></fn></fc><fn=0><fc=$fgAlt,$bg> </fc></fn><fc=$songName,$bg>%s </fc><fc=$textColor,$bg>[%s][%s]</fc><fc=$bg><fn=1></fn></fc>" "$song_name" $(mocp -Q %ct) $(mocp -Q %tt)
            for i in $(seq 1 $result); do echo -n " "; done
        fi

        if [ "$1" == "moc" ]; then
            notify-send.sh -R /tmp/id_file -t 2000 -i multimedia-player "$song_name"
        fi
    else
        echo ""
    fi
fi
