#!/usr/bin/env bash

source $HOME/.config/xmonad/xmobar_scripts/colors

case "$1" in
    updates)
        file="/tmp/updates"
        if [[ -z $(cat $file) ]]; then
            notify-send.sh -R /tmp/id_file -i dialog-information "System up to date"
        else
            temp=$(cat $file)
            notify-send.sh -R /tmp/id_file -t 3000 -i dialog-information "Available updates" "$temp"
        fi
        ;;
    *)
        response="$(curl -m 3 -L xanmod.org)"
        if [ $? -eq 0 ]; then
          major=$(echo "$response" | grep -A 5 "Stable Mainline" | grep -o "key_text.*" | cut -d '=' -f2)
        fi
        release="$(uname -r | sed "s/$major\(.*\)-xanmod1/\1/")"

        if [ ! -z "$major" ] && [ ! "$major" == "$release" ]; then
          n_update_xanmod=1
          update_xanmod="xanmod-kernel ${release} -> ${major}"
        else
          n_update_xanmod=0
          update_xanmod=""
        fi
        updates_arch=$(checkupdates 2> /dev/null)
        n_updates_arch=$(echo "$updates_arch" | sed '/^$/d' | wc -l)

        updates_arch=$(checkupdates 2> /dev/null)
        updates_aur=$(yay -Qua 2> /dev/null)
        n_updates_aur=$(echo "$updates_aur" | sed '/^$/d' | wc -l)

        n_updates=$(("$n_updates_arch" + "$n_updates_aur" + "$n_update_xanmod"))

        if [ -z "$updates_arch" ] && [ -z "$updates_aur" ]; then
          printf "%s" "$update_xanmod" > /tmp/updates
        elif [ -z "$updates_arch" ]; then
          printf "%s\n%s" "$updates_aur" "$update_xanmod" > /tmp/updates
        elif [ -z "$updates_aur" ]; then
          printf "%s\n%s" "$updates_arch" "$update_xanmod" > /tmp/updates
        else
          printf "%s\n%s\n%s" "$updates_arch" "$updates_aur" "$update_xanmod" > /tmp/updates
        fi

        if [ "$n_updates" -eq 0 ]; then
            echo "<fc=$bg><fn=1></fn></fc><fc=$fgAlt,$bg><fn=0> </fn></fc><fc=$bg><fn=1></fn></fc>"
        else
            echo "<fc=$bg><fn=1></fn></fc><fc=$fgYellow,$bg><fn=0> </fn>${n_updates}</fc><fc=$bg><fn=1></fn></fc>"
        fi
        ;;
esac
