#!/usr/bin/env bash

source $HOME/.config/xmonad/xmobar_scripts/colors

function icon {
    case "$1" in
        01d ) icon=" "
            ;;
        01n ) icon=" "
            ;;
        02d ) icon=" "
            ;;
        02n ) icon=" "
            ;;
        03? ) icon=" "
            ;;
        04? ) icon=" "
            ;;
        09? ) icon=" "
            ;;
        10d ) icon=" "
            ;;
        10n ) icon=" "
            ;;
        11? ) icon=" "
            ;;
        13? ) icon=" "
            ;;
        50? ) icon=" "
            ;;
    esac
    echo "<fc=$bg><fn=1></fn></fc><fn=0><fc=$fg,$bg>$icon</fc></fn>"
}

function save_to_file {
    printf "\n<b> Today:</b>\n    \n\n"" Feels_like: %.0fºC\n Wind Speed %.2fkm/h\n Humidity: %s%%" \
        "$weather_feels_like" "$weather_wind_speed" "$weather_humidity" > /tmp/weather

    printf "\n\n<b> 3 Hours Forecast:</b>\n          " >> /tmp/weather

    printf "\n\n Temp: %.0fºC\n Description: %s\n Feels Like: %.0fºC" \
        "$(echo "$forecast_temp"|bc)" "$forecast_desc" "$(echo "$forecast_feels_like"|bc)" >> /tmp/weather

    printf "\n Wind Speed: %.2fkm/h\n Humidity: %s%%" "$(echo "$forecast_wind_speed*3.6"|bc)" "$forecast_humidity" >> /tmp/weather
}

case "$1" in
    extended )
        if [ -f /tmp/weather.bk ]; then
            temp="/tmp/weather.bk"
        else
            temp="/tmp/weather"
        fi
        notify-send.sh -R /tmp/id_file -t 3000 "Extended weather" "$(cat $temp)" -o "Openweather.org:firefox https://openweathermap.org/city/3860259"
        ;;
    * )
        weather_url="https://api.openweathermap.org/data/2.5/weather?id=3860259&appid=$(cat "$HOME"/.config/xmonad/xmobar_scripts/apikey)&units=metric"
        forecast_url="https://api.openweathermap.org/data/2.5/forecast?id=3860259&appid=$(cat "$HOME"/.config/xmonad/xmobar_scripts/apikey)&units=metric"

        # Current weather
        weather_info=$(curl "$weather_url")
        weather_desc=$(echo "$weather_info" | jq '.weather[0].description' | sed -e 's/^"//' -e 's/"$//')
        weather_icon_code=$(echo "$weather_info" | jq '.weather[0].icon' | sed -e 's/^"//' -e 's/"$//')
        weather_temp=$(echo "$weather_info" | jq '.main.temp' | sed -e 's/^"//' -e 's/"$//')
        weather_icon=$(icon "$weather_icon_code")
        printf "%s<fc=$textColor,$bg> %.0fºC, %s</fc><fc=$bg><fn=1></fn></fc>" "$weather_icon" "$(echo "$weather_temp"|bc)" "${weather_desc}"

        # Extended
        weather_feels_like="$(echo "$(echo "$weather_info" | jq '.main.feels_like' | sed -e 's/^"//' -e 's/"$//')"|bc)"
        weather_wind_speed="$(echo "$(echo "$weather_info" | jq '.wind.speed' | sed -e 's/^"//' -e 's/"$//')*3.6"|bc)"
        weather_humidity=$(echo "$weather_info" | jq '.main.humidity' | sed -e 's/^"//' -e 's/"$//')

        # Forecast
        forecast_info=$(curl "$forecast_url")
        forecast_temp=$(echo "$forecast_info" | jq '.list[0].main.temp')
        forecast_desc=$(echo "$forecast_info" | jq '.list[0].weather[].description' | sed -e 's/^"//' -e 's/"$//')
        forecast_feels_like=$(echo "$forecast_info" | jq '.list[0].main.feels_like')
        forecast_humidity=$(echo "$forecast_info" | jq '.list[0].main.humidity')
        forecast_wind_speed=$(echo "$forecast_info" | jq '.list[0].wind.speed')

        if [ -f /tmp/weather ]; then
            cp /tmp/weather /tmp/weather.bk
            save_to_file
            rm /tmp/weather.bk
        else
            save_to_file
        fi
        ;;
esac
