#!/usr/bin/env bash

set -x

function clone_repositories() {
  git clone https://github.com/xmonad/xmonad
  git clone https://github.com/xmonad/xmonad-contrib
  git clone https://codeberg.org/xmobar/xmobar.git
}

function setup_ghcup() {
  regex="ghc|cabal|hls"

  hash ghcup &> /dev/null
  if [ $? -eq 1 ]; then
    yay -S ghcup-hs-bin --noconfirm
  fi

  readarray -t to_install < <(ghcup list | awk '/✗.*recommended/ {print $0}' | grep -E -o ".*\s+(${regex}).*" | tr -s ' ' | cut -d ' ' -f 3,4)

  echo "Install ghc, cabal and hls"
  for pkg in "${to_install[@]}"; do
    ghcup install $pkg
  done
}

function copy_ghc_executables() {
  sudo cp ~/.ghcup/ghc/9.4.8/bin/ghc-9.4.8 /usr/bin/ghc
  sudo cp ~/.ghcup/ghc/9.4.8/bin/ghci-9.4.8 /usr/bin/ghci
  sudo cp ~/.ghcup/ghc/9.4.8/bin/ghc-pkg-9.4.8 /usr/bin/ghc-pkg
}

function create_project_file() {
  echo "packages: ./*.cabal xmonad/xmonad.cabal xmonad-contrib/xmonad-contrib.cabal xmobar/xmobar.cabal" > cabal.project
}

function create_cabal_file() {
  {
    echo "cabal-version:      3.0"
    echo "name:               xmonad-config"
    echo "version:            0.1.0.0"
    echo ""
    echo "common warnings"
    echo "    ghc-options: -Wall"
    echo ""
    echo "executable xmonad-config"
    echo "    import:           warnings"
    echo "    main-is:          xmonad.hs"
    echo "    build-depends:"
    echo "        base ^>=4.17.2.1,"
    echo "        xmonad ^>=0.18.0.9,"
    echo "        xmonad-contrib ^>=0.18.1"
    echo ""
    echo "    other-modules:"
    echo "        Misc,"
    echo "        Bindings,"
    echo "        Layouts,"
    echo "        ManageHooks,"
    echo "        Scratchpads,"
    echo "        StartupHooks,"
    echo "        Workspaces"
    echo ""
    echo "    hs-source-dirs: . lib"
    echo ""
    echo "    default-language: Haskell2010"

  } > xmonad-config.cabal
}

function install_xmonad_xmobar() {
  echo "Update Cabal"
  cabal update

  echo "Install Xmonad"
  cabal install --package-env=$HOME/.config/xmonad xmonad
  cabal install --package-env=$HOME/.config/xmonad --lib base xmonad xmonad-contrib

  echo "Install Xmobar"
  cabal install --flags="with_xpm with_xrender -with_weather -with_rtsopts" --package-env=$HOME/.config/xmobar xmobar
}

function copy_xmonad_executables() {
  sudo cp ~/.local/bin/xmonad /usr/bin
  sudo cp ~/.local/bin/xmobar /usr/bin
}

function create_build_file() {
  {
    echo "cabal build"
  } > build
  chmod +x build
}

function recompile() {
  if [ ! -d ~/.cache/xmonad ]; then
    mkdir ~/.cache/xmonad
  fi
  ln -s ~/.config/xmonad/dist-newstyle/build/x86_64-linux/ghc-9.4.8/xmonad-config-0.1.0.0/x/xmonad-config/build/xmonad-config/xmonad-config ~/.cache/xmonad/xmonad-x86_64-linux
  ./recompile
}

function add_hie_file() {
  {
    echo "cradle:"
    echo "  cabal:"
    echo "    - path: ".""
    echo "      component: "xmonad-config:exe:xmonad-config""
    echo
  } > hie.yaml
}

function create_desktop_file() {
  if [ ! -f /usr/share/xsessions/xmonad.desktop ]; then
    {
      echo "[Desktop Entry]"
      echo "Encoding=UTF-8"
      echo "Type=Application"
      echo "Name=Xmonad"
      echo "Comment=Lightweight X11 tiled window manager written in Haskell"
      echo "Exec=xmonad"
      echo "Icon=xmonad"
      echo "Terminal=false"
      echo "StartupNotify=false"
      echo "Categories=Application;"
    } > xmonad.desktop
    if [ ! -d /usr/share/xsessions/ ]; then
      sudo mkdir /usr/share/xsessions/
    fi
    sudo mv ./xmonad.desktop /usr/share/xsessions/
    rm -rf ./xmonad.desktop
  fi
}

clone_repositories
setup_ghcup
copy_ghc_executables
create_project_file
create_cabal_file
install_xmonad_xmobar
copy_xmonad_executables
create_build_file
recompile
add_hie_file
create_desktop_file
