# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Do not inserts a blank line between shell prompts
add_newline = false

# Custom prompt
format = """\
[](fg:#E7D7AD)\
[ ](bg:#E7D7AD fg:#3a495c)\
[](bg:#3a495c fg:#E7D7AD)\
$username\
[](bg:#b04c0b fg:#3a495c)\
$directory\
[](bg:#285423 fg:#b04c0b)\
$git_branch\
$git_status\
$git_commit\
$git_state\
[](fg:#285423 bg:#E7D7AD)\
[  ](bg:#E7D7AD fg:#3a495c)\
[ ](fg:#E7D7AD)\
"""

[username]
show_always = true
style_user = "bg:#3a495c"
style_root = "bg:#db3e2c"
format = '[ $user ]($style)'

[directory]
truncation_length = 2
truncation_symbol = ""
home_symbol = "~"
style = "bg:#b04c0b"
format = "[ $path ]($style)"

[directory.substitutions]
"Documents" = " Documents"
"Downloads" = " Downloads"
"Music" = " Music"
"Pictures" = "  Pictures"
"Videos" = "  Videos"
"Dropbox" = " Dropbox"

[git_branch]
symbol = ""
style = "bg:#285423"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#285423"
conflicted=""
ahead=""
behind=""
diverged=""
untracked=""
up_to_date=""
stashed=""
modified=""
staged=""
format = '[$all_status$ahead_behind ]($style)'

[git_commit]
style = "bg:#285423"
format = '[$hash]($style)'

[git_state]
style = "bg:#285423"
format = '[$state]($style)'

