# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Do not inserts a blank line between shell prompts
add_newline = false

# Custom prompt
format = """\
[](fg:color_red)\
$conda\
[](bg:#E7D7AD fg:color_red)\
[  ](bg:#E7D7AD fg:#3a495c)\
[](bg:#3a495c fg:#E7D7AD)\
$username\
[](bg:#b04c0b fg:#3a495c)\
$directory\
[](bg:#285423 fg:#b04c0b)\
$git_branch\
$git_status\
$git_commit\
$git_state\
[](fg:#285423 bg:#E7D7AD)\
[  ](bg:#E7D7AD fg:#3a495c)\
[ ](fg:#E7D7AD)\
$line_break $character\
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[line_break]
disabled = false

[conda]
symbol = ' '
style = 'bg:color_red'
format = '[$symbol$environment]($style)'

[username]
show_always = true
style_user = "bg:#3a495c"
style_root = "bg:#db3e2c"
format = '[ $user ]($style)'

[directory]
truncation_length = 2
truncation_symbol = ""
home_symbol = "~"
style = "bg:#b04c0b"
format = "[ $path ]($style)"

[directory.substitutions]
"Documents" = " Documents"
"Downloads" = " Downloads"
"Music" = " Music"
"Pictures" = "  Pictures"
"Videos" = "  Videos"
"Dropbox" = " Dropbox"

[git_branch]
symbol = ""
style = "bg:#285423"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#285423"
conflicted=""
ahead=""
behind=""
diverged=""
untracked=""
up_to_date=""
stashed=""
modified=""
staged=""
format = '[$all_status$ahead_behind ]($style)'

[git_commit]
style = "bg:#285423"
format = '[$hash]($style)'

[git_state]
style = "bg:#285423"
format = '[$state]($style)'

[character]
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
