#!/usr/bin/env bash

case $1 in
	mountPendrive )
	  udisksctl mount -b /dev/sdb?
	  ;;
	mountAndroid )
	  jmtpfs "$HOME/.Smartphone"
	  ;;
	umountPendrive )
	  umount /dev/sdb?
	  ;;
	umountAndroid)
		fusermount -u "$HOME/.Smartphone"
esac
