#!/usr/bin/env bash

function restart_xmonad {
	yay -Syyu --devel --noconfirm; xmonad --recompile && xmonad --restart
}

if [ -z "$1" ]
then
	restart_xmonad
elif [ "$1" = "-i" ]
then
	if [ -z "$2" ]
	then
		echo "You must type a pkg name"
	else
		mapfile -t array < <(echo "$2" | tr ',' "\n")
		size=${#array[@]}
		if [ "$size" -gt 1 ]
		then
			word="packages are"
		else
			word="package is"
		fi
		echo "|${array[*]} $word not gonna be updated|"
		restart_xmonad
	fi
else
	echo "Invalid option"
fi
