#!/usr/bin/env bash

if [ -z $1 ]
then
	yay -Syyu --devel --noconfirm; xmonad --recompile && xmonad --restart
elif [ $1 = "-i" ]
then
	if [ -z $2 ]
	then
		echo "You must type a pkg name"
	else
		array=($(echo $2 | tr ',' "\n"))
		size=${#array[@]}
		if [ $size -gt 1 ]
		then
			word="packages are"
		else
			word="package is"
		fi
		echo "|${array[@]} $word not gonna be updated|"
		yay -Syyu --devel --ignore $2 --noconfirm; xmonad --recompile && xmonad --restart
	fi
else
	echo "Invalid option"
fi
