#!/usr/bin/env bash

function name_ext(){
	name=$(echo "$1" | cut -d '.' -f1)
	ext=$(echo "$1" | cut -d '.' -f2)
}

function convert {
	printf "\nConverting to mp3\n\n"
	ffmpeg -i "$1".wav "$1".mp3 2> /dev/null
	printf "\nNormalize volume\n\n"
	mp3gain -c -r -p -d 6 "$1".mp3
	printf "\nMoving file to ~/Music\n\n"
	mv "$1".mp3 ~/Music
}

function with_vocals {
	bt_name_v="$name"" backingtrack (vocals)"
	ffmpeg -f concat -safe 0 -i vocals vocals.wav 2> /dev/null
	ffmpeg -i bass.wav -i drums.wav -i piano.wav -i vocals.wav -filter_complex amix=inputs=4:duration=longest "$bt_name_v".wav 2> /dev/null
	convert "$bt_name_v"
}

function without_vocals {
	bt_name="$name"" backingtrack (no vocals)"
	ffmpeg -i bass.wav -i drums.wav -i piano.wav -filter_complex amix=inputs=3:duration=longest "$bt_name".wav 2> /dev/null
	convert "$bt_name"
}

function clean {
	trm -rf bass drums vocals piano bass.wav drums.wav vocals.wav piano.wav "$name"_00* "$bt_name".wav "$bt_name_v" output
}

function usage {
	printf "Usage: \n\tbacking_track [Options]\n"
	printf "\nOptions: \n"
	printf "\t-o <value> --option <value>\t 1: With Vocals,2: Without Vocals,3:Both\n"
	printf "\t-s <value> --song <value>\n"
}

if [ "$#" -lt 4 ]; then
	usage
	exit 0
fi

short=os:
long=option,song:

if ! getopt -n "$0" -o $short --long "$long" -- "$@" >/dev/null
then
	exit 1
fi

while true;
do
	case "$1" in
		-o | --option )
			shift
			option=$1
			if [ ! $((option)) -gt 0 ] || [ ! $((option)) -lt 4 ]; then
				echo Invalid option
				exit 1
			fi
			shift
			;;
		-s | --song )
			shift
			song=$1
			name_ext "$(basename "$song")"
			if [ -e "$song" ]; then
				if [ "$ext" != "mp3" ]; then
				echo Invalid format for a song.
				exit 1
				fi
			else
				echo File doesn\'t exist
				exit 1
			fi
			shift
			;;
		* )
			shift
			break
			;;
	esac
done

if [[ $(command -v spleeter) != "" ]]; then
	ffmpeg -i "$song" -f segment -segment_time 90 -c copy "$name""_%03d"".$ext"  2> /dev/null
	for i in "$name"_*.mp3
	do
		spleeter separate -i "$i" -p spleeter:5stems -o output
	done

	for i in "output/$name"_*/*
	do
		if [[ $i =~ "bass" ]]; then
			printf "file '%s'\n" ./"$i" >> bass
		elif [[ $i =~ "drums" ]]; then
			printf "file '%s'\n" ./"$i" >> drums
		elif [[ $i =~ "piano" ]]; then
			printf "file '%s'\n" ./"$i" >> piano
		elif [[ $i =~ "vocals" ]]; then
			printf "file '%s'\n" ./"$i" >> vocals
		fi
	done

	ffmpeg -f concat -safe 0 -i bass bass.wav 2> /dev/null
	ffmpeg -f concat -safe 0 -i drums drums.wav 2> /dev/null
	ffmpeg -f concat -safe 0 -i piano piano.wav 2> /dev/null

	case "$option" in
		1 ) with_vocals
			clean
			;;
		2 )
			without_vocals
			clean
			;;
		* )
			with_vocals
			without_vocals
			clean
			;;
	esac

else
	echo Command spleeter not found
	exit 1
fi
