#!/usr/bin/env bash

function name_ext(){
	name=$(echo "$1" | cut -d '.' -f1)
	ext=$(echo "$1" | cut -d '.' -f2)
}

if [ -z "$1" ]; then
	echo You must specify the length of the chunks in seconds and the song
else
	name_ext "$2"
	ffmpeg -i "$2" -f segment -segment_time "$1" -c copy "$name""_%03d"".$ext"
fi

for i in "$name"_*.mp3
do
	spleeter separate -i "$i" -p spleeter:4stems -o output
done

for i in "output/$name"_*/*
do
	if [[ $i =~ "bass" ]]; then
		printf "file '%s'\n" ./"$i" >> bass
	elif [[ $i =~ "drums" ]]; then
		printf "file '%s'\n" ./"$i" >> drums
	elif [[ $i =~ "vocals" ]]; then
		printf "file '%s'\n" ./"$i" >> vocals
	fi
done

ffmpeg -f concat -safe 0 -i bass bass.wav
ffmpeg -f concat -safe 0 -i drums drums.wav
ffmpeg -f concat -safe 0 -i vocals vocals.wav

ffmpeg -i bass.wav -i drums.wav -i vocals.wav -filter_complex amix=inputs=3:duration=longest "$name"_backing_track.wav

rm bass drums vocals bass.wav drums.wav vocals.wav "$name"_00*
