#!/usr/bin/env bash

lints=("shellcheck" "sh" "gcc" "clang" "cppcheck" "ghc" "hlint" "stylish-haskell" "checkstyle" "google-java-format" "perl-critic" "flake8" "yapf" "vint")

for linter in ${lints[*]}
do
	output=$(yay -Qi $linter 2>&1)
	if [[ $output =~ "was not found" ]]
	then
		yay -S $linter
	else
		echo "$linter already installed"
	fi
done
