#!/usr/bin/env bash

device=$(pactl list sources | head -3 | tail -1 | cut -d':' -f2) 

date=$(date +%y-%m-%d_%H-%M)

ffmpeg -video_size 1920x1080 -framerate 25 -f x11grab -i :0.0+0,0 -f pulse -ac 2 -i $device "$HOME/Videos/$date.mkv"
