#!/usr/bin/env bash

path="$HOME/.local/bin/"

for i in *
do
	if [  "$i" != "symbolic_links" ]
	then
		if [ -e "$path$i" ]
		then
			rm "$path$i"
		fi
		ln -s "$PWD"/"$i" "$path$i"
		echo "Added command \"$i\""
	fi
done
