#!/usr/bin/env bash

for i in *
do
	if [  "$i" != "symbolic_links" ]
	then
		if [ -e /usr/bin/"$i" ]
		then
			sudo rm /usr/bin/"$i"
		fi
		sudo ln -s "$PWD"/"$i" /usr/bin/"$i"
		echo "Added command \"$i\""
	fi
done
