#!/usr/bin/env bash

function update {
	yay -Syyu --devel --noconfirm; xmonad --recompile && xmonad --restart
}

function clean {
	yay -Sc --noconfirm
	temp=$(yay -Qtdq | tr '\n' ' ')
	yay -Rns $(echo "$temp") --noconfirm
	paccache -r
}

function ignore {
	temp=$(printf "%s," $(yay -Qsq $1))
	mapfile -t array < <(echo "$temp" | tr ',' "\n")
	size=${#array[@]}
	if [ "$size" -gt 1 ]
	then
	   word="packages are"
	else
	   word="package is"
	fi
	echo "|${array[*]} $word not gonna be updated|"
	update
}

function usage {
	printf "Usage: \n\tarch_update [Options]\n"
	printf "\nOptions: \n"
	printf "\t-c --clean \n"
	printf "\t-i <value> --ignore <value>\n"
}

args=("$@")

if [ "$#" -lt 2 ]; then
	if [ "$#" -eq 0 ]; then
		args+=("-a")
	elif [ ! "$1" = "-c" ]; then
		usage
		exit 0
	fi
fi

set -- ${args[*]}

short=aci:
long=clean,ignore:

if ! getopt -n "$0" -o $short --long "$long" -- "$@" >/dev/null
then
	exit 1
fi

while true;
do
	case "$1" in
		-a | --all )
			shift 
			update
			shift
			;;
		-c | --clean ) 
			shift
			clean
			shift
			;;
		-i | --ignore )
			shift
			regex=$1
			ignore "$regex"
			shift
			;;
		* ) 
			shift
			break
			;;
	esac
done
