#!/usr/bin/env bash

function usage {
    printf "Usage: \n\t./$0 [Options]\n"
    printf "\nOptions: \n"
    printf "\t-r <value> --regex <value>\n"
}

if [ "$#" -lt 2 ]; then
    usage
    exit 0
fi

short=r:
long=regex:

if ! getopt -n "$0" -o $short --long "$long" -- "$@" >/dev/null
then
    exit 1
fi

while true;
do
    case "$1" in
        -r | --regex )
            shift
            regex=$1
            shift
            ;;
        * )
            shift
            break
            ;;
    esac
done

if [ ! -d "$HOME/.Smartphone/SD card" ]; then
    go-mtpfs -usb-timeout=60000 $HOME/.Smartphone 2>/dev/null &disown
    sleep 1
fi

find . -maxdepth 1 -regex $regex -exec rsync -auvP {} ~/.Smartphone/SD\ card \;
