#!/usr/bin/env bash

apps=("astyle" "bashdb" "bash-language-server" "ctags" "cmake " "hasktags" "gdb" "haskell-language-server-bin" "strace" "valgrind" "efm-langserver-git" "flawfinder" "digestif-git")

for app in ${apps[*]}
do
	output=$(yay -Qqe "$app" 2>&1)
	if [[ $output =~ "was not found" ]]
	then
		yay -S "$app"
	else
		echo "$app already installed"
	fi
done
