#!/usr/bin/bash

disconnected=$(xrandr --query | awk '/HDMI.*disconnected/ {print $1}')

if [ -z "$disconnected" ]; then
    hash envycontrol
    if [[ $? -eq 0 ]]; then
        if [[ $(envycontrol -q | cut -d ' ' -f 5) == "nvidia" ]]; then
            # Reduce lag with GLX backend
            nvidia-settings -a 'AllowFlipping=0'
            # Full composition pipeline
            nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }"
            # Avoid setting mode if it is already in 1920x1080
            xrandr | awk '/HDMI/ {print $0}' | grep 1920
            if [ $? -ne 0 ]; then
              xrandr --output HDMI-0 --mode 1920x1080 --rate 144
            fi
        else
            xrandr --output HDMI-1-0 --mode 1920x1080 --rate 144 --primary --same-as eDP-1
        fi
    fi
fi

