#!/usr/bin/env bash

hash reflector
[[ $? -eq 1 ]] && (printf "\nreflector is not installed\nInstalling..."; yay -S reflector)

sudo reflector --verbose -l 20 -f 15 --sort rate --protocol https --save /etc/pacman.d/mirrorlist
