#!/usr/bin/env bash

hash reflector
[[ $? -eq 1 ]] && (printf "\nreflector is not installed\nInstalling..."; yay -S reflector)

sudo reflector --country Argentina --country Brazil --age 12 --protocol https --sort rate --save /etc/pacman.d/mirrorlist 
