#!/usr/bin/env bash

lints=("shellcheck" "sh" "gcc" "clang" "cppcheck" "ghc" "hlint" "stylish-haskell" "google-java-format" "flake8" "yapf" "vint" "texlab" "proselint" "checkmake" "prettier")

for linter in ${lints[*]}
do
	output=$(yay -Qqe "$linter" 2>&1)
	if [[ $output =~ "was not found" ]]
	then
		yay -S "$linter"
	else
		echo "$linter already installed"
	fi
done
