#!/usr/bin/env sh

function usage {
    printf "Usage: \n\t.${0} [Options]\n"
    printf "\nOptions: \n"
    printf "\t-v <value> --video <value>\n"
}

if [ "$#" -lt 2 ]; then
    usage
    exit 0
fi

short=v:
long=video:

if ! getopt -n "$0" -o $short --long "$long" -- "$@" >/dev/null
then
    exit 1
fi

while true;
do
    case "$1" in
        -v | --video )
            shift
            video="$1"
            shift
            ;;
        * )
            break
            ;;
    esac
done

fps=$(mediainfo "$video" | awk '/FPS/ {print $4}' | head -n 1)
fps_final=$(printf "%.0f" $fps)
name=$(echo "$video" | cut -d '.' -f 1)
ext=$(echo "$video" | cut -d '.' -f 2)

ffmpeg -i "${video}" -vsync cfr -r "${fps_final}" -pix_fmt yuv420p "${name}_normalized.${ext}"

fps_half=$(printf "%.1f" $(echo "$fps_final/2" | bc -l))

ffmpeg -i "${name}_normalized.${ext}" -vf fps=${fps_half} -vsync cfr "${name}_reduced.${ext}"

scenedetect -i "${name}_reduced.${ext}" split-video

mkdir -p "${name}_scenes"
mv *_reduced-Scene* "${name}_scenes"

counter=1
for i in "${name}_scenes"/*; do
  dir=${i%/*}
  file=${i##*/}
  mkdir -p "${dir}/${counter}"
  mv "$i" "${dir}/${counter}"
  root=$(pwd)
  cd "${dir}/${counter}"
  $HOME/.scripts/extract_images -f *
  cd "${root}"
  counter=$((counter+1))
done
