#!/usr/bin/env bash

x=900
y=25
DATE="$(date +"%a %d %H:%M")"

case "$1" in
    --popup)
        yad --calendar --undecorated --fixed --close-on-unfocus --no-buttons \
            --posx=$x --posy=$y > /dev/null
        ;;
    *)
        echo " $DATE"
        ;;
esac
